import { DonationFoundation } from '@/types/common';

export const DONATION_FOUNDATIONS: DonationFoundation[] = [
  {
    id: 1,
    name: '금성노인복지관',
    foundationUrl: 'https://www.gsnb.or.kr/',
    category: '독거노인',
    title: '독거노인을 위한 소화기',
    mainImage: '/images/donationFoundation/독거노인/독거노인1.jpeg',
    bodyImage: '/images/donationFoundation/독거노인/독거노인2.jpeg',
    donationPeriod: { start: '2024-04-07', end: '2024-05-12' },
    donationCount: 0,
    donationGoal: 1000,
    description:
      '살다 보면 크고 작은 재난 상황을 마주하게 되는 경우가 많습니다. 화재로 인한 안전 사고는 언제 일어날지 아무도 예측할 수 없기 때문에, 그중에서도 연세가 있고 혼자 사시는 분들께 갑작스럽게 닥치는 화재는 정말 위험합니다. 작은 불씨로 시작하지만 몸이 불편하시거나 그렇지 않더라도 놀란 탓에 순간적으로 아무런 장비 없이 대처를 하지 못해 작은 불이 큰 불로 키워지게 됩니다.\n\n이런 경우를 대비하여 집안에 작으면서도 편리한 투척용 소화기가 있으면 독거노인이 큰 힘을 들이지 않으시더라도 응급 상황에 사용하실 수 있으리라 봅니다.\n\n주거 환경이 열악하고 화재에 취약한 80여 명의 어르신에게 투척용 소화기를 제공해 드리려 합니다. 직원들이 어르신 가정에 직접 방문하여 설치해 드리고, 사용 방법을 알려 드리고자 합니다. 의성군 지역 내 어르신께 소화기를 선물해 주시면 80여 명 어르신의 안전을 지킬 수 있습니다. 많은 후원 부탁드립니다.',
    comments: [],
    createdAt: '2024-03-27',
  },
  {
    id: 2,
    name: '라이프오브더칠드런',
    foundationUrl: 'https://www.lifeofthechildren.org/',
    category: '지구촌',
    title: '아이들은 가족과 밥 한끼가 그립습니다',
    mainImage: '/images/donationFoundation/지구촌/지구촌1.jpeg',
    bodyImage: '/images/donationFoundation/지구촌/지구촌2.jpeg',
    donationPeriod: { start: '2024-04-07', end: '2024-06-20' },
    donationCount: 0,
    donationGoal: 1000,
    description:
      '엘살바도르 "산페드로 페룰라판(San pedro perulapan)"지역에는 25,000명의 주민과 산간에 자리 잡은 8개의 작은 마을이 모여있습니다. 주변에 ‘산마틴’이라는 큰 시장이 있는데, 과거에 갱단들이 시장을 장악한 이래. 폭동과 폭력의 잔재가 여전히 남아 있습니다. 그 이후부터 경찰이 체포·수색영장이나 명확한 증거 없이 심증만으로 주민들을 체포하는 경우가 많아져, 하루아침 부모님과 이별하는 아이들이 늘어나고 있습니다.\n\n생활의 세 가지 기본 요소 중 ‘의식주’가 있지만, 아이들에겐 무엇보다 ‘맛있는 음식’이 중요할 것입니다. 엘살바도르에도 우리나라 설날과 같이 가족들이 모이는 연휴가 있습니다. 다가오는 3월, 따뜻해지는 날씨와 함께 아이들에게도 맛있는 음식과 함께 봄이 찾아올 수 있도록 마음을 모아주세요.\n\n여러분이 내밀어주신 따스한 손길은 지역 학교 아이들과 "산페드로시 파라이소" 마을 가정에 지급될 예정입니다. 어지럽고 혼란스러운 시기에 주민들이 힘을 얻을 수 있도록, 아이들이 눈치 보지 않고 든든한 한 끼를 먹을 수 있도록, 지금 여러분의 따스한 손길을 내밀어주세요.',
    comments: [],
    createdAt: '2024-04-02',
  },
  {
    id: 3,
    name: '안심제1종합사회복지관',
    foundationUrl: 'https://iwel.or.kr/main/main.html',
    category: '지구촌',
    title: '지구를 위한 환경보호, 친환경 보드게임으로 배우자!',
    mainImage: '/images/donationFoundation/지구촌/지구촌3.jpeg',
    bodyImage: '/images/donationFoundation/지구촌/지구촌4.jpeg',
    donationPeriod: { start: '2024-04-07', end: '2024-07-01' },
    donationCount: 0,
    donationGoal: 1000,
    description:
      '2023년 7월 27일, UN 사무총장은 지구 온난화 시대가 끝나고 지구 열대화 시대가 시작되었다고 경고했습니다. 문제는 폭염 뿐만 아니라 가뭄, 폭우, 홍수, 태풍 등 기후 변화가 연속되고 있고, 이로 인한 피해가 심각해지고 있다는 것입니다. 이러한 기후 변화의 심각성은 2000년대가 되며 ‘기후위기’로 표현되었고, 최근에는 ‘기후재앙’으로까지 표현되고 있습니다. ‘기후정의’는 기후 변화가 사회경제적으로 열악한 사람에게 더 많은 영향을 미친다는 의미를 담고 있습니다.\n\n지역주민이 직접 기획하고 참여하는 환경보드게임 리더 교육, 마을 인권교육, 기후 위기 대응 환경교육, 지역주민이 함께 환경 문제에 관심있는 지역주민을 발굴하고 연계하는 활동(지역주민과 함께하는 환경 보드게임, 환경 보드게임 대회 및 환경 캠페인 운영)을 통하여 지역주민의 기후 변화 인식 및 친환경 실천력 강화의 기회를 마련하고, 주민 간 소통에 따라 주체적으로 활동을 진행하고자 합니다.\n\n안심 마을 지역주민이 친환경 실천력을 높이고 기후 위기에 대응할 수 있도록 많은 관심과 사랑 부탁드립니다 :)',
    comments: [],
    createdAt: '2024-04-02',
  },
  {
    id: 4,
    name: '사회복지법인 어린이재단',
    foundationUrl: 'https://www.childfund.or.kr/regularSpon/regular.do?mcode=7&utm_source=google_pc&utm_medium=search_ad&utm_campaign=%EC%B4%88%EB%A1%9D%EC%9A%B0%EC%82%B0_%EB%B8%8C%EB%9E%9C%EB%93%9C_pc&utm_content=%EB%B8%8C%EB%9E%9C%EB%93%9C_%EC%9E%90%EC%82%AC%EB%AA%85&utm_term=%EC%B4%88%EB%A1%9D%EC%9A%B0%EC%82%B0&gad_source=1&gclid=Cj0KCQjw5cOwBhCiARIsAJ5njuYb407UJC6LK6twoNZEF5Sjuo3NjbxP-qMDu7k7gO4Om79r7RyFdcAaAp97EALw_wcB',
    category: '지구촌',
    title: '석현이의 꿈은 가족을 지켜줄 수 있는 태권도 선수!',
    mainImage: '/images/donationFoundation/지구촌/지구촌5.jpeg',
    bodyImage: '/images/donationFoundation/지구촌/지구촌6.jpeg',
    donationPeriod: { start: '2024-04-07', end: '2024-06-01' },
    donationCount: 0,
    donationGoal: 1000,
    description:
      '엄마가 집안일을 할 때면 쪼르르 달려와 청소와 집안일도 함께하는 석현이와 삼 남매. 때로는 엄마의 청소 아르바이트에 가서 함께 일손이 되어주기도 합니다. 이렇게 서로를 위하여 언제나 똘똘 뭉쳐 어려움을 이겨내는 단란한 다섯 가족이지만 가족들이 마주하는 현실은 차갑기만 합니다.\n\n차가운 겨울 바람을 이겨내기에는 역부족인 낡은 집, 나날이 올라가는 생활비에 끊겨버린 가스, 보일러를 아끼려 찬물로 빨래하는 일상. 치킨집, 딸기밭, 식당 보조 등 아이들을 위해서라면 못할 일이 없는 엄마지만 아이들이 커갈수록 필요한 건 점점 많아지기에 엄마는 오늘도 한계를 느낍니다.\n\n석현이네 가족이 생활비 걱정 없이 꿈을 키우며 완전한 가족으로 성장할 수 있도록 여러분의 따뜻한 응원을 보내주세요.',
    comments: [],
    createdAt: '2024-04-01',
  },
  {
    id: 5,
    name: '사회복지법인 희망나누리',
    foundationUrl:'http://www.hope1203.org/default/',
    category: '장애인',
    title: '장애를 넘어 제주로, 가족과 함께하는 특별한 여행',
    mainImage: '/images/donationFoundation/장애인/장애인1.jpeg',
    bodyImage: '/images/donationFoundation/장애인/장애인2.jpeg',
    donationPeriod: { start: '2024-04-07', end: '2024-04-23' },
    donationCount: 0,
    donationGoal: 1000,
    description:
      '장애를 가진 아이를 둔 엄마로서의 삶은 상당한 무게감을 안겨 줍니다. 사람이 많은 곳에 아이와 함께 갈 때면 혹시 민폐가 되지는 않을까 걱정이 들기도 하고, 장애를 가진 아이를 보며 세상 가장 불행한 엄마처럼 바라보는 사람들의 시선을 받기도 합니다. 이런 상황 속에서도 아이에게 아름다운 순간을 보여주고 싶어 따뜻한 바람이 불어오고, 푸른 새싹이 돋아나는 날 아이에게 "날씨가 좋은데 산책이나 갈까?" 혹은 "쉬는 날 여행을 갈까?"라고 묻지만, 누구나 쉽게 할 수 있는 대답조차 못하는 아이를 바라보는 엄마의 마음은 지쳐가기 일쑤입니다.\n\n매일이 반복되고 지루해져 지쳐가기만 하는 일상에서 여행은 비장애인에게 설렘입니다. 어느 곳을 갈지, 무엇을 먹을지 생각만으로 행복한 고민이 부풀어 오릅니다. 큰 고민이라 생각하던 일을 사소한 일처럼 만들어 버리기도 하는 마법 같은 경험을 하기도 합니다.\n\n세상에 어느 누구도 가치 없는 삶은 없습니다. 경험해 보지 못하여 어려운 중증장애인에게 우리의 경험을 배울 수 있는 기회를 선물해 주세요. 가두어진 세상이 전부인 그들에게는 다양한 실외활동과 평범한 우리의 일상에 함께 소통하는 경험이 필요합니다.\n\n작은 나눔의 실천, 큰 희망이 됩니다.\n\n',
    comments: [],
    createdAt: '2024-04-04',
  },
  {
    id: 6,
    name: '사단법인 여성환경연대',
    foundationUrl:'https://www.ecofem.or.kr/',
    category: '여성',
    title: '여성청소년에게 체험형 월경 교육의 기회를 마련해 주세요.',
    mainImage: '/images/donationFoundation/여성/여성1.jpeg',
    bodyImage: '/images/donationFoundation/여성/여성2.jpeg',
    donationPeriod: { start: '2024-04-07', end: '2024-06-10' },
    donationCount: 0,
    donationGoal: 1000,
    description:
      '여성환경연대는 월경 교육이 필요한 현장에서 사용할 수 있도록 월경 교육 매뉴얼과 활용 방법을 설명한 동영상이 담긴 월경 교육 키트를 배포하려 합니다. 월경 교육 키트에는 월경 교육 경험자를 비롯하여 교육자 혹은 사회복지사 등이 직접 교육을 진행할 수 있도록 ‘월경 교육 매뉴얼’이 담겨있으며, 교육자가 매뉴얼 및 교육 진행 방법을 ‘동영상으로 학습할 수 있도록’ 준비할 예정입니다.\n\n월경 교육 키트는 교육자용과 청소년용으로 제작하여 월경 교육 진행이 지속적으로 이루어져야 하는 ▶월경 교육이 가능한 교육자, ▶청소년 쉼터, ▶보육원 및 공동생활가정, ▶도서산간 지역 학교 등의 신청을 받아 전달될 예정입니다.\n\n월경과 여성의 몸에 대한 이해를 높이고 다양한 월경용품을 직접 만져봄으로써 자신에게 적합한 월경용품을 찾아보는 체험형 월경 교육. 이러한 교육을 통하여 월경과 다른 몸에 대한 차이가 존중되는 사회. 청소년의 월경할 권리가 보장받을 수 있도록 정보접근성을 높이고 실천력을 길러낼 수 있도록 따뜻한 응원을 보내주세요.',
    comments: [],
    createdAt: '2024-04-07',
  },
];
